"""unique dni cuit

Revision ID: 238cbd6c7dac
Revises: 8f011440419a
Create Date: 2026-01-31 21:24:01.640406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238cbd6c7dac'
down_revision = '8f011440419a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_clients_dni'), ['dni'])
        batch_op.create_unique_constraint(batch_op.f('uq_clients_cuit'), ['cuit'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_clients_cuit'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_clients_dni'), type_='unique')
    # ### end Alembic commands ###
