"""unique dni cuit

Revision ID: 238cbd6c7dac
Revises: 8f011440419a
Create Date: 2026-01-31 21:24:01.640406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238cbd6c7dac'
down_revision = '8f011440419a'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name if bind is not None else ""

    # Si ya hay duplicados en datos de prueba, resolvemos dejando solo 1 registro
    # con el DNI/CUIT y seteando NULL en el resto (evita que falle la migración).
    # En producción, la app ya impide crear duplicados.
    if dialect == "sqlite":
        op.execute(
            """
            UPDATE clients
            SET dni = NULL
            WHERE dni IS NOT NULL
              AND dni IN (
                SELECT dni FROM clients WHERE dni IS NOT NULL GROUP BY dni HAVING COUNT(*) > 1
              )
              AND id NOT IN (
                SELECT MIN(id) FROM clients WHERE dni IS NOT NULL GROUP BY dni
              )
            """
        )
        op.execute(
            """
            UPDATE clients
            SET cuit = NULL
            WHERE cuit IS NOT NULL
              AND cuit IN (
                SELECT cuit FROM clients WHERE cuit IS NOT NULL GROUP BY cuit HAVING COUNT(*) > 1
              )
              AND id NOT IN (
                SELECT MIN(id) FROM clients WHERE cuit IS NOT NULL GROUP BY cuit
              )
            """
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_clients_dni'), ['dni'])
        batch_op.create_unique_constraint(batch_op.f('uq_clients_cuit'), ['cuit'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_clients_cuit'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_clients_dni'), type_='unique')
    # ### end Alembic commands ###
