"""invoice soft delete

Revision ID: 8f011440419a
Revises: a1a04643b48b
Create Date: 2026-01-31 21:10:58.266033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f011440419a'
down_revision = 'a1a04643b48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_deleted_by_user_id'), ['deleted_by_user_id'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_invoices_deleted_by_user_id_users'),
            'users',
            ['deleted_by_user_id'],
            ['id'],
        )

    # limpia server_default en engines que lo mantienen
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('is_deleted', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoices_deleted_by_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_deleted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_is_deleted'))
        batch_op.drop_column('deleted_by_user_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
    # ### end Alembic commands ###
