"""add payment metadata

Revision ID: a1a04643b48b
Revises: 5351b57c08ac
Create Date: 2026-01-31 21:00:03.127106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a04643b48b'
down_revision = '5351b57c08ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_payments_created_by_user_id_users'),
            'users',
            ['created_by_user_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_created_by_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_paid_at'))
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('paid_at')
    # ### end Alembic commands ###
